server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: modern-donor-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,openapi
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Modern FHIR Donor Service API
    description: FHIR R4 compliant blood banking donor service
    version: 1.0.0
    contact:
      name: Arc One Blood Banking
      email: support@arcone.com

logging:
  level:
    com.arcone.modern: DEBUG
    org.springframework.web: INFO
