apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-donor-service
  namespace: api
  labels:
    app: modern-donor-service
    version: v1
    component: patient-management
    domain: api
    compliance: fhir-r4
    service-type: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modern-donor-service
      version: v1
  template:
    metadata:
      labels:
        app: modern-donor-service
        version: v1
        component: patient-management
        domain: api
        compliance: fhir-r4
        service-type: spring-boot
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: modern-donor-service
          image: modern-donor-service:latest
          imagePullPolicy: Never # For local development
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SERVER_PORT
              value: "8082"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,metrics,prometheus,openapi"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: modern-donor-service
  namespace: api
  labels:
    app: modern-donor-service
    service: modern-donor-service
    domain: api
    compliance: fhir-r4
    service-type: spring-boot
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: modern-donor-service
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: modern-donor-service
  namespace: api
spec:
  hosts:
    - modern-donor-service
    - modern-donor-service.api.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: modern-donor-service
            port:
              number: 8082
      timeout: 30s
      retries:
        attempts: 3
        perTryTimeout: 10s
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: modern-donor-service
  namespace: api
spec:
  host: modern-donor-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 2
    loadBalancer:
      simple: LEAST_CONN
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: modern-donor-service
  namespace: api
spec:
  selector:
    matchLabels:
      app: modern-donor-service
  mtls:
    mode: PERMISSIVE
