apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-governance
  namespace: api-governance
  labels:
    app: api-governance
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-governance
      version: v1
  template:
    metadata:
      labels:
        app: api-governance
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/health/metrics"
    spec:
      serviceAccountName: api-governance
      containers:
        - name: api-governance
          image: api-governance:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
          envFrom:
            - configMapRef:
                name: api-governance-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          volumeMounts:
            - name: api-specs-storage
              mountPath: /data/api-specs
      volumes:
        - name: api-specs-storage
          persistentVolumeClaim:
            claimName: api-specs-pvc
