apiVersion: v1
kind: Namespace
metadata:
  name: api-governance
  labels:
    name: api-governance
    istio-injection: enabled
  annotations:
    description: "Microservices API Governance Platform"
