apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-specs-pvc
  namespace: api-governance
  labels:
    app: api-governance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
